site_name: CLP
docs_dir: ./docs
pages:

    - Apresentação: 
       - Geral: index.md
       - CLP-coordenada: index_CLPcoord.md
       - CLP-via: index_CLPvia.md

    - Especificações:
      - Geral: spec01-hub.md
      - Referências: spec05-referencias.md
    - Apêncides:
      - Siglas: spec04ap01-siglas.md  

    - Créditos: assets/README.md

extra_javascript:
    - assets/leaflet-bing-layer.min.js
